/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheVertexInstituteRouteImport } from './routes/the-vertex-institute'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MarketingSystemsRouteImport } from './routes/marketing-systems'
import { Route as GrowthConsultingRouteImport } from './routes/growth-consulting'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as BookACallRouteImport } from './routes/book-a-call'
import { Route as AiSolutionsRouteImport } from './routes/ai-solutions'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TheVertexInstituteRoute = TheVertexInstituteRouteImport.update({
  id: '/the-vertex-institute',
  path: '/the-vertex-institute',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingSystemsRoute = MarketingSystemsRouteImport.update({
  id: '/marketing-systems',
  path: '/marketing-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthConsultingRoute = GrowthConsultingRouteImport.update({
  id: '/growth-consulting',
  path: '/growth-consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const BookACallRoute = BookACallRouteImport.update({
  id: '/book-a-call',
  path: '/book-a-call',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSolutionsRoute = AiSolutionsRouteImport.update({
  id: '/ai-solutions',
  path: '/ai-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-solutions': typeof AiSolutionsRoute
  '/book-a-call': typeof BookACallRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/growth-consulting': typeof GrowthConsultingRoute
  '/marketing-systems': typeof MarketingSystemsRoute
  '/portfolio': typeof PortfolioRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/the-vertex-institute': typeof TheVertexInstituteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-solutions': typeof AiSolutionsRoute
  '/book-a-call': typeof BookACallRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/growth-consulting': typeof GrowthConsultingRoute
  '/marketing-systems': typeof MarketingSystemsRoute
  '/portfolio': typeof PortfolioRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/the-vertex-institute': typeof TheVertexInstituteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-solutions': typeof AiSolutionsRoute
  '/book-a-call': typeof BookACallRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/growth-consulting': typeof GrowthConsultingRoute
  '/marketing-systems': typeof MarketingSystemsRoute
  '/portfolio': typeof PortfolioRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/the-vertex-institute': typeof TheVertexInstituteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-solutions'
    | '/book-a-call'
    | '/case-studies'
    | '/contact'
    | '/growth-consulting'
    | '/marketing-systems'
    | '/portfolio'
    | '/resources'
    | '/services'
    | '/the-vertex-institute'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-solutions'
    | '/book-a-call'
    | '/case-studies'
    | '/contact'
    | '/growth-consulting'
    | '/marketing-systems'
    | '/portfolio'
    | '/resources'
    | '/services'
    | '/the-vertex-institute'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-solutions'
    | '/book-a-call'
    | '/case-studies'
    | '/contact'
    | '/growth-consulting'
    | '/marketing-systems'
    | '/portfolio'
    | '/resources'
    | '/services'
    | '/the-vertex-institute'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiSolutionsRoute: typeof AiSolutionsRoute
  BookACallRoute: typeof BookACallRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  GrowthConsultingRoute: typeof GrowthConsultingRoute
  MarketingSystemsRoute: typeof MarketingSystemsRoute
  PortfolioRoute: typeof PortfolioRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRoute
  TheVertexInstituteRoute: typeof TheVertexInstituteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/the-vertex-institute': {
      id: '/the-vertex-institute'
      path: '/the-vertex-institute'
      fullPath: '/the-vertex-institute'
      preLoaderRoute: typeof TheVertexInstituteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing-systems': {
      id: '/marketing-systems'
      path: '/marketing-systems'
      fullPath: '/marketing-systems'
      preLoaderRoute: typeof MarketingSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth-consulting': {
      id: '/growth-consulting'
      path: '/growth-consulting'
      fullPath: '/growth-consulting'
      preLoaderRoute: typeof GrowthConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-a-call': {
      id: '/book-a-call'
      path: '/book-a-call'
      fullPath: '/book-a-call'
      preLoaderRoute: typeof BookACallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-solutions': {
      id: '/ai-solutions'
      path: '/ai-solutions'
      fullPath: '/ai-solutions'
      preLoaderRoute: typeof AiSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiSolutionsRoute: AiSolutionsRoute,
  BookACallRoute: BookACallRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  GrowthConsultingRoute: GrowthConsultingRoute,
  MarketingSystemsRoute: MarketingSystemsRoute,
  PortfolioRoute: PortfolioRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRoute,
  TheVertexInstituteRoute: TheVertexInstituteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
